export const ColumnNames = {
	NAME: 'Наименование',
	TYPE: 'Тип СИ',
	FACTORY_NUMBER: 'Заводской номер',
	MEASUREMENT_LIMITS: 'Пределы измерений',
	ACCURACY: 'Точность, цена деления, погрешность',
	STATE_REGISTER: 'Госреестр СИ',
	MANUFACTURER: 'Изготовитель',
	YEAR_OF_ISSUE: 'Год выпуска',
	VERIFICATION_DATE: 'Дата поверки (калибровки)',
	INTER_VERIFICATION_INTERVAL: 'Межповерочный интервал',
	NEXT_VERIFICATION_DATE: 'Следующая поверка (калибровка)',
	PLACE: 'Место нахождения',
	PERSON: 'ФИО сотрудника',
	NOTES: 'Примечание',
}
