export const ColumnNames = Object.freeze({
	NAME: 'Наименование' as const,
	TYPE: 'Тип СИ' as const,
	FACTORY_NUMBER: 'Заводской номер' as const,
	MEASUREMENT_LIMITS: 'Пределы измерений' as const,
	ACCURACY: 'Точность, цена деления, погрешность' as const,
	STATE_REGISTER: 'Госреестр СИ' as const,
	MANUFACTURER: 'Изготовитель' as const,
	YEAR_OF_ISSUE: 'Год выпуска' as const,
	VERIFICATION_DATE: 'Дата поверки (калибровки)' as const,
	INTER_VERIFICATION_INTERVAL: 'Межповерочный интервал' as const,
	NEXT_VERIFICATION_DATE: 'Следующая поверка (калибровка)' as const,
	PLACE: 'Место нахождения' as const,
	PERSON: 'ФИО сотрудника' as const,
	NOTES: 'Примечание' as const,
})
